# Generated by Django 4.0.3 on 2022-03-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_detail', '0002_delete_time_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_detail',
            new_name='StudentDetail',
        ),
    ]
